<!doctype html>
<html class="no-js" lang="">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{title}}</title>
  <meta name="author" content="author">
  <meta name="keywords" content="keywords">
  <meta name="description" content="description">
  <meta name="HandheldFriendly" content="True">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <meta name="format-detection" content="telephone=no, email=no, adress=no">
  <link rel="icon" type="/images/x-icon" href="../favicon.ico">

  <css src="../components/reset.pcss" chunk="vendor" cache="true"></css>
  <!-- CSS_FILE -->
  
</head>
<body ontouchstart="">
  {% block body %}{% endblock %}
</body>
  <!-- JS_FILE -->
  
</html>
